SELECT
  COUNT(*)
FROM public.orders
WHERE EXTRACT(YEAR FROM created_at) = 2024
  AND EXTRACT(MONTH FROM created_at) = 2
UNION ALL
SELECT
  COUNT(*)
FROM public.orders
WHERE EXTRACT(YEAR FROM created_at) = 2023
  AND EXTRACT(MONTH FROM created_at) = 2